name       : perl-file-slurp
version    : 9999.19
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/U/UR/URI/File-Slurp-9999.19.tar.gz : ce29ebe995097ebd6e9bc03284714cdfa0c46dc94f6b14a56980747ea3253643
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Simple and Efficient Reading/Writing/Modifying of Complete Files
description: |
    Simple and Efficient Reading/Writing/Modifying of Complete Files.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
