name       : perl-file-slurp
version    : '9999.32'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/C/CA/CAPOEIRAB/File-Slurp-9999.32.tar.gz : 4c3c21992a9d42be3a79dd74a3c83d27d38057269d65509a2f555ea0fb2bc5b0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Simple and Efficient Reading/Writing/Modifying of Complete Files
description: |
    Simple and Efficient Reading/Writing/Modifying of Complete Files.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
