name       : perl-file-slurp
version    : '9999.29'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/C/CA/CAPOEIRAB/File-Slurp-9999.29.tar.gz : 0e6e47e0bba639e37e51fdc7a43b187cd90ac642e4baa13a7185bc6c223e19c7
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Simple and Efficient Reading/Writing/Modifying of Complete Files
description: |
    Simple and Efficient Reading/Writing/Modifying of Complete Files.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
